// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNMeJt_PjbKlhzWV8H8hiJVejpyG2OnJk',
    appId: '1:1039673248032:web:fd95599be4a8a570ea6f45',
    messagingSenderId: '1039673248032',
    projectId: 'flutterfirebase-881f5',
    authDomain: 'flutterfirebase-881f5.firebaseapp.com',
    storageBucket: 'flutterfirebase-881f5.firebasestorage.app',
    measurementId: 'G-F5YV1VK3ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX9xIKsYJZTTjZvHjm48TC3-lml01qBHw',
    appId: '1:1039673248032:android:b584ff81ea0f2207ea6f45',
    messagingSenderId: '1039673248032',
    projectId: 'flutterfirebase-881f5',
    storageBucket: 'flutterfirebase-881f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYx-pZL3BiRMP_ERTOiGeQZp8z9Q-WiF0',
    appId: '1:1039673248032:ios:504c773365bafbecea6f45',
    messagingSenderId: '1039673248032',
    projectId: 'flutterfirebase-881f5',
    storageBucket: 'flutterfirebase-881f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppDatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYx-pZL3BiRMP_ERTOiGeQZp8z9Q-WiF0',
    appId: '1:1039673248032:ios:504c773365bafbecea6f45',
    messagingSenderId: '1039673248032',
    projectId: 'flutterfirebase-881f5',
    storageBucket: 'flutterfirebase-881f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppDatos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNMeJt_PjbKlhzWV8H8hiJVejpyG2OnJk',
    appId: '1:1039673248032:web:bc65b8f0d672a475ea6f45',
    messagingSenderId: '1039673248032',
    projectId: 'flutterfirebase-881f5',
    authDomain: 'flutterfirebase-881f5.firebaseapp.com',
    storageBucket: 'flutterfirebase-881f5.firebasestorage.app',
    measurementId: 'G-QESQ8ZCL1V',
  );

}